- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

- platform: template
  sensors:
    inst_2_stage_percent:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 }}
        {%- else -%}        
        {{
        (states('counter.inst_2_stage_idle_time')|int(0) /
        states('input_number.inst_2_stage_length')|int(0) ) * 100
        | round(0)
        }}
        {%- endif -%}

    inst_2_session_percent:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 | int(0) }}
        {%- else -%}        
        {{
        (states('sensor.inst_2_total_idle_time')|int(0) /
        states('sensor.inst_2_total_idle_time_to_8')|int(0) * 100)
        | round(0)
        }}
        {%- endif -%}

    inst_2_seconds_since_session_start:
      value_template: >-
        "{{ now().timestamp() -
        as_timestamp(states('input_datetime.inst_2_session_start_time'), 0) }}"
        | int(0) }}"

    inst_2_total_idle_time_to_8:
      value_template: "{{ states('input_number.inst_2_stage_length')|int(0) * 5 }}"

    inst_2_total_idle_time:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 | int(0) }}
        {%- else -%}       
        {{
        ((states('counter.stage_inst_2')| int(0) - 3) *
        states('input_number.inst_2_stage_length')|int(0)) +
        states('counter.inst_2_stage_idle_time')|int(0)
        }}
        {%- endif -%}
        
# {%- if (states('counter.stage_inst_2')|int < 2) -%}
# {{ 0 | int }}
# {%- else -%}
# {{
# (states('counter.stage_inst_2')| int - 2
# *
# states('input_number.inst_2_stage_length')| int
# +
# states('counter.inst_2_stage_idle_time')| int )
# |
# }}
# {%- endif -%}

#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
# inst_2_time_idle:
#   value_template: >-
#     "{{ ((states('counter.stage_inst_2')|int -3)
#     *
#     states('input_number.inst_2_stage_length')|int)
#     +
#     states('counter.inst_2_stage_idle_time')|int }}"

# binary_sensor:
#   - platform: template
#     sensors:
#       is_stage4:
#         value_template: >
#           "{{ (states('timer')) | string != (states('sensor.stage_4_length')) | string }}"
#       is_stage5:
#         value_template: >
#           "{{ (states('monitor_level_detailed')) | string != (states('sensor.stage_5_length')) | string }}"
#       is_stage6:
#         value_template: >
#           "{{ (states('monitor_level_detailed')) | string != (states('sensor.stage_6_length')) | string }}"
#       is_stage7:
#         value_template: >
#           "{{ (states('monitor_level_detailed')) | string != (states('sensor.stage_7_length')) | string }}"
#       is_stage8:
#         value_template: >
#           "{{ (states('monitor_level_detailed')) | string != (states('sensor.stage_8_length')) | string }}"

#      inst2_timer_began:
#        friendly_name: "[Inst 2] Timer Seconds Elapsed"
#        value_template: "{{ ((as_timestamp(now()) - as_timestamp(states.timer.instance_2_stage_timer.last_changed)) ) | int }}"

#      inst2_stage_remaining_sec:
#        friendly_name: "[Inst 2] Stage Remaining Seconds"
#        value_template: >-
#          {%- if (states['timer.instance_2_stage_timer'].attributes.duration == "none") or (states['timer.instance_2_stage_timer'].state == "idle") -%}
#          {{ 0 | int }}
#          {%- else -%}
#          {{ ((((states['timer.instance_2_stage_timer'].attributes.duration).split(':')[0] |int * 60 * 60) + ((states['timer.instance_2_stage_timer'].attributes.duration).split(':')[1] |int * 60 ) + ((states['timer.instance_2_stage_timer'].attributes.duration).split(':')[2] |int)) - (as_timestamp(now()) | float - states['sensor.inst2_timer_began'].state | float) ) | int }}
#          {%- endif -%}

# - platform: template
# sensors:
#   monitor_level:
#     unique_id: "monitor_level_1"
#     friendly_name: "Monitor Level"
#     unit_of_measurement: "Alert Level"
#     value_template: "{{ states('counter.stage') }}"
#   monitor_level_detailed:
#     unique_id: "monitor_level_detailed"
#     friendly_name: "Monitor Level, Detailed"
#     unit_of_measurement: "Alert Level"
#     value_template: "{{ states('counter.motion_time_total_seconds') }}"
#   time_formatted:
#     friendly_name: "Time"
#     value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%-I:%M %p') }}"
#     icon_template: mdi:calendar-clock
#   stage_4_length:
#     friendly_name: "Stage 4 Starts"
#     unique_id: "stage_4_length"
#     unit_of_measurement: "seconds"
#     value_template: "{{ states('input_number.stage_length') | int | float - states('input_number.pir_buffer') | int }}"
#   stage_5_length:
#     friendly_name: "Stage 5 Starts"
#     unique_id: "stage_5_length"
#     unit_of_measurement: "seconds"
#     value_template: "{{ states('input_number.stage_length') | int * 2 | float - states('input_number.pir_buffer') | int }}"
#   stage_6_length:
#     friendly_name: "Stage 6 Starts"
#     unique_id: "stage_6_length"
#     unit_of_measurement: "seconds"
#     value_template: "{{ states('input_number.stage_length') | int * 3 | float - states('input_number.pir_buffer') | int }}"
#   stage_7_length:
#     friendly_name: "Stage 7 Starts"
#     unique_id: "stage_7_length"
#     unit_of_measurement: "seconds"
#     value_template: "{{ states('input_number.stage_length') | int * 4 | float - states('input_number.pir_buffer') | int }}"
#   stage_8_length:
#     friendly_name: "Stage 8 Starts"
#     unique_id: "stage_8_length"
#     unit_of_measurement: "seconds"
#     value_template: "{{ states('input_number.stage_length') | int * 5 | float - states('input_number.pir_buffer') | int }}"
