- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "date_time_utc"
    - "date_time_iso"
    - "time_date"
    - "time_utc"

- platform: template
  sensors:
    inst_2_stage_percent:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 }}
        {%- else -%}        
        {{
        (states('counter.inst_2_stage_idle_time')|int(0) /
        states('input_number.inst_2_stage_length')|int(0) ) * 100
        | round(0)
        }}
        {%- endif -%}

    inst_2_session_percent:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 | int(0) }}
        {%- else -%}        
        {{
        (states('sensor.inst_2_total_idle_time')|int(0) /
        states('sensor.inst_2_total_idle_time_to_8')|int(0) * 100)
        | round(0)
        }}
        {%- endif -%}

    inst_2_seconds_since_session_start:
      value_template: >-
        "{{ now().timestamp() -
        as_timestamp(states('input_datetime.inst_2_session_start_time'), 0) }}"
        | int(0) }}"

    inst_2_total_idle_time_to_8:
      value_template: "{{ states('input_number.inst_2_stage_length')|int(0) * 5 }}"

    inst_2_total_idle_time:
      value_template: >-
        {%- if (states('counter.stage_inst_2')|int(0) < 3) -%}
        {{ 0 | int(0) }}
        {%- else -%}       
        {{
        ((states('counter.stage_inst_2')| int(0) - 3) *
        states('input_number.inst_2_stage_length')|int(0)) +
        states('counter.inst_2_stage_idle_time')|int(0)
        }}
        {%- endif -%}